global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # cAdvisor - Container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 5s
    metrics_path: /metrics

  # Node Exporter - System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Deployment metrics from webhook dispatcher (disabled until metrics file is available)
  # - job_name: 'deployment-metrics'
  #   static_configs:
  #     - targets: ['localhost:9090']  # Self-scraping
  #   file_sd_configs:
  #     - files: ['/tmp/deployment_metrics.prom']
  #       refresh_interval: 30s

  # Traefik metrics
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']
    scrape_interval: 5s

  # Database metrics (hvis du aktiverer metrics eksporters)
  # - job_name: 'mariadb'
  #   static_configs:
  #     - targets: ['mariadb-exporter:9104']
  
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['postgres-exporter:9187']

  # Redis metrics
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis-exporter:9121']

# Alertmanager configuration (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           # - alertmanager:9093