# Traefik middleware definitions
http:
  middlewares:
    # Security headers
    secure-headers:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
          - POST
          - DELETE
        accessControlMaxAge: 100
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        referrerPolicy: "same-origin"
        customResponseHeaders:
          X-Frame-Options: "SAMEORIGIN"
          X-Content-Type-Options: "nosniff"
          X-XSS-Protection: "1; mode=block"

    # Rate limiting for APIs
    api-rate-limit:
      rateLimit:
        burst: 100
        average: 50

    # Redirect HTTP to HTTPS
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true

    # CORS for APIs (configure per-app as needed)
    cors-allow-all:
      headers:
        accessControlAllowOriginList:
          - "*"
        accessControlAllowMethods:
          - "GET"
          - "POST"
          - "PUT"
          - "DELETE"
          - "OPTIONS"
        accessControlAllowHeaders:
          - "Content-Type"
          - "Authorization"
          - "X-Requested-With"
          
    # Restrictive CORS (use this template for production apps)
    cors-restrictive:
      headers:
        accessControlAllowOriginList:
          - "https://your-infrastructure-domain.com"
          - "https://www.your-infrastructure-domain.com"
        accessControlAllowMethods:
          - "GET"
          - "POST"
          - "PUT"
          - "DELETE"
          - "OPTIONS"
        accessControlAllowHeaders:
          - "Content-Type"
          - "Authorization"
          - "X-Requested-With"

  # Global HTTP redirect
  routers:
    http-catchall:
      rule: "hostregexp(`{host:.+}`)"
      entryPoints:
        - "web"
      middlewares:
        - "redirect-to-https"
      service: api@internal

# TLS configuration
tls:
  options:
    default:
      sslProtocols:
        - "TLSv1.2"
        - "TLSv1.3"
      cipherSuites:
        - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
        - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"